In [1]:
%cd /home/badourj/Parallel-Dynamic-Sparse-Training
import os
import matplotlib.pyplot as plt

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
%load_ext autoreload
%autoreload 2

/home/badourj/Parallel-Dynamic-Sparse-Training

In [2]:
!pip install pandas matplotlib numpy

Looking in indexes: https://__token__:****@gitlab.utsp.utwente.nl/api/v4/groups/271/-/packages/pypi/simple
Requirement already satisfied: pandas in ./venv/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: matplotlib in ./venv/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: numpy in ./venv/lib/python3.12/site-packages (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./venv/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in ./venv/lib/python3.12/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./venv/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import json
import glob
import pandas as pd 
import numpy as np
from collections import defaultdict
from benchmark.plots.matrix_matrix import *


def rename_colum(df, old_name, new_name):

    df["Type"] = df["Type"].apply(lambda x: x if x != old_name else new_name)



prefix = "log_mult_incl_cupy"
# prefix = "aug-1-log_mult_incl_cupy"

df = pd.DataFrame()
for sparse_type in [
        # "test_sparse_cupy",
        # "test_sparse_cupy_csr",
        # "test_sparse_torch_csr",
        # "test_jax_bsr",
        "test_sparse_ut",
        # "test_sparse_torch", 
        "test_sputnik",
        # "test_dense",
        
]:
    
    dfc = pd.read_csv(f"./benchmark/{prefix}-{sparse_type}.csv")
        
    dfc["Type"] = dfc["isSparse"].apply(lambda x: sparse_type.replace("test_","")).copy()
    if sparse_type == "test_dense":
        dfc_temp = dfc[dfc["isSparse"] == "Dense"]
        dfc_temp["cuda_elapsed_time"] = dfc_temp["cuda_elapsed_time"] * 1.99
        dfc_temp["isSparse"] =dfc_temp["Type"] = "Dense+Mask"
        dfc = pd.concat([dfc, dfc_temp], axis=0)
        
    # dfc["sparsity_level"] = dfc["sparsity_level"] * 100 / (dfc["sparsity_level"].max())
    df = pd.concat([df, dfc])
    # display(df.tail())
    # if dense_level not in df['dense_level'].tolist():
    #     print(sparse_type)
    #     print(df['dense_level'].tolist())
    #     raise RuntimeError("Dense level is not in df")

rename_colum(df, "sparse_ut", "SpMM_COO(Snack)")
rename_colum(df, "Dense+Mask", "DenseMM+Mask")

rename_colum(df, "dense", "DenseMM")
rename_colum(df, "sparse_cupy", "SpMM_COO(Cupy)")
rename_colum(df, "sparse_torch", "SpMM_COO(Torch)")
rename_colum(df, "sparse_cupy_csr", "SpMM_CSR(Cupy)")
rename_colum(df, "jax_bsr", "SpMM_BSR(Jax)")
rename_colum(df, "Sputnik", "SpMM_CSR(Torch)")

rename_colum(df, "sparse_sputnik_csr", "SpMM_CSR(Torch)")

display(df.tail())

FileNotFoundError: [Errno 2] No such file or directory: './benchmark/log_mult_incl_cupy-test_sputnik.csv'

In [9]:
df

,isSparse,dense_level,sparsity_level,time,cuda_elapsed_time,rep,batch_size,Type
0,SparseUT,500x500,0.0,0.049576,49.646591,0,1,SpMM_COO(Snack)
1,SparseUT,500x500,0.0,0.002444,4.869120,1,1,SpMM_COO(Snack)
2,SparseUT,500x500,24.0,0.003129,3.981504,0,1,SpMM_COO(Snack)
3,SparseUT,500x500,24.0,0.003096,3.741696,1,1,SpMM_COO(Snack)
4,SparseUT,500x500,48.0,0.003116,3.136512,0,1,SpMM_COO(Snack)
...,...,...,...,...,...,...,...,...
2107,Sputnik,10000x10000,99.0,0.000840,18.319361,1,1024,sputnik
2108,Sputnik,10000x10000,99.5,0.000538,11.469920,0,1024,sputnik
2109,Sputnik,10000x10000,99.5,0.000525,11.453664,1,1024,sputnik
2110,Sputnik,10000x10000,99.9,0.000630,4.851744,0,1024,sputnik
2111,Sputnik,10000x10000,99.9,0.000546,4.837376,1,1024,sputnik

In [3]:
dens = df.dense_level.unique()
" & ".join(dens)

'500x500 & 1000x1000 & 5000x5000 & 7500x7500 & 8500x8500 & 10000x10000'

In [11]:
def produce_latex_table(df, dense_level, batch_sizes=[1024], first=False):
    
    types = list(df.Type.unique())
    dfc = df[(df.dense_level == dense_level) & df.batch_size.isin(batch_sizes)][['Type', 'cuda_elapsed_time', 'sparsity_level']]
    
    dfc = dfc.groupby(['sparsity_level', 'Type']).mean().reset_index()[['Type', 'cuda_elapsed_time', 'sparsity_level']]
    # filter
    dfc = dfc[dfc.sparsity_level == 95]
    dfc = dfc.sort_values(by='Type', ascending=False)
    col = "cuda_elapsed_time" + " " + dense_level
    dfc[col] = dfc["cuda_elapsed_time"]
    return dfc[(["Type"] if first else []) + [col]]

dfc_s = [
produce_latex_table(df, '500x500', first=True),
produce_latex_table(df, '1000x1000'),

produce_latex_table(df, '5000x5000'),
produce_latex_table(df, '7500x7500'),
    produce_latex_table(df, '8500x8500'),
produce_latex_table(df, '10000x10000'),
]
dfc = pd.concat(dfc_s, axis=1)
for _, row in dfc.iterrows():
    lst = (list(row))
    def truncate(x):
        if isinstance(x, str):
            return x
        return str(round(x,2))
    s = " & ".join(map(truncate, lst))
    print(s.replace("_", "\_"))
dfc

sputnik & 0.82 & 2.1 & 22.26 & 50.89 & 61.21 & 86.8

<>:31: SyntaxWarning: invalid escape sequence '\_'
<>:31: SyntaxWarning: invalid escape sequence '\_'
/tmp/ipykernel_752158/1104849014.py:31: SyntaxWarning: invalid escape sequence '\_'
  print(s.replace("_", "\_"))

,Type,cuda_elapsed_time 500x500,cuda_elapsed_time 1000x1000,cuda_elapsed_time 5000x5000,cuda_elapsed_time 7500x7500,cuda_elapsed_time 8500x8500,cuda_elapsed_time 10000x10000
9,sputnik,0.82176,2.096672,22.260688,50.893217,61.206415,86.801918

In [5]:
df[
    (df.rep ==1) &
    # (df.batch_size == 1) & 
    (df.sparsity_level.map(int).isin([90, 95, 99]))
]# .sparsity_level.unique()

,isSparse,dense_level,sparsity_level,time,cuda_elapsed_time,rep,batch_size,Type
17,SparseUT,500x500,90.0,0.002558,2.570592,1,1,SpMM_COO(Snack)
19,SparseUT,500x500,95.0,0.002264,2.277312,1,1,SpMM_COO(Snack)
27,SparseUT,500x500,99.0,0.002266,2.277568,1,1,SpMM_COO(Snack)
29,SparseUT,500x500,99.5,0.002284,2.294784,1,1,SpMM_COO(Snack)
31,SparseUT,500x500,99.9,0.002283,2.292928,1,1,SpMM_COO(Snack)
...,...,...,...,...,...,...,...,...
2097,Sputnik,10000x10000,90.0,0.000559,209.139526,1,1024,sputnik
2099,Sputnik,10000x10000,95.0,0.000480,92.999680,1,1024,sputnik
2107,Sputnik,10000x10000,99.0,0.000840,18.319361,1,1024,sputnik
2109,Sputnik,10000x10000,99.5,0.000525,11.453664,1,1024,sputnik
2111,Sputnik,10000x10000,99.9,0.000546,4.837376,1,1024,sputnik

In [6]:
df[(df.Type == 'DenseMM') & (df.batch_size == 1) & (df.sparsity_level.map(int) == 90)]

Empty DataFrame
Columns: [isSparse, dense_level, sparsity_level, time, cuda_elapsed_time, rep, batch_size, Type]
Index: []

In [ ]:


dfc = df[(df.sparsity_level >= 50) & (df.sparsity_level <= 100)]

fig = plt.figure(figsize=(14, 7))
axes = defaultdict(dict)
gs = fig.add_gridspec(2, 2) 
axes[0][2] = fig.add_subplot(gs[0, 0])
axes[1][2] = fig.add_subplot(gs[0, 1])
axes[0][3] = fig.add_subplot(gs[1, 0])
axes[1][3] = fig.add_subplot(gs[1, 1])
categories=[
        'DenseMM', 'SpMM_COO(Snack)', 'SpMM_COO(Cupy)' ,'SpMM_CSR(Cupy)', 'SpMM_CSR(Torch)', 'SpMM_BSR(Jax)', 'SpMM_COO(Torch)', "DenseMM+Mask" 
    ]
_ = create_single_plot_for_batches(
    dfc, 
    dense_level, 
    "cuda_elapsed_time",
    [1],
    figsize=(7, 5), 
    log=True,
    title="SpMM/DenseMM (batch size = 1)",
    batch_needed=False,
    categories=categories,
    ax=axes[0][2]
)

_ = create_single_plot_for_batches(
    dfc, 
    dense_level, 
    "cuda_elapsed_time",
    [4],
    figsize=(7, 5), 
    log=True,
    title="SpMM/DenseMM (batch size = 4)",
    batch_needed=False,
    categories=categories,
    ax=axes[1][2]
)


_ = create_single_plot_for_batches(
    dfc, 
    dense_level, 
    "cuda_elapsed_time",
    [16],
    figsize=(7, 5), 
    log=True,
    title="SpMM/DenseMM (batch size = 16)",
    batch_needed=False,
       categories=categories,
    ax=axes[0][3]
)

_ = create_single_plot_for_batches(
    dfc, 
    dense_level, 
    "cuda_elapsed_time",
    [1, 32],
    figsize=(7, 5), 
    log=True,
    title="SpMM/DenseMM (batch size = 32)",
    batch_needed=False,
       categories=categories,
    ax=axes[1][3],
    legend_place="lower left",
)
for k in axes.keys():
    for v in axes[k].values():
        v.legend().set_visible(False)
legend_labels = categories
legend_colors = plt.cm.tab10.colors
from matplotlib.patches import Patch

# Create custom legend handles
custom_handles = [Patch(color=color, label=label) for color, label in zip(legend_colors, legend_labels)]
fig.legend(handles=custom_handles,
           ncol=4,
          loc='lower center',
           bbox_to_anchor=(0.5, -0.1),
           frameon=True)

# plt.tight_layout(rect=[0, 0, 1, 0.95])
for ax in [ axes[0][3], axes[1][3]]:
    
    ax.set_xlabel('Sparsity')
axes[0][3].set_ylabel('CUDA time')
axes[0][2].set_ylabel('CUDA time')
plt.show()

fig.savefig("./figures/SpMM vs DenseMM-hor.pdf", bbox_inches='tight')
plt.show()

In [ ]:


dfc = df[(df.sparsity_level >= 50) & (df.sparsity_level <= 100)]

fig = plt.figure(figsize=(4, 7))
axes = defaultdict(dict)
gs = fig.add_gridspec(2, 1) 
# axes[0][2] = fig.add_subplot(gs[0, 0])
# axes[1][2] = fig.add_subplot(gs[1, 0])
axes[0][3] = fig.add_subplot(gs[0, 0])
axes[1][3] = fig.add_subplot(gs[1, 0])
categories=[
        'DenseMM', 'SpMM_COO(Snack)', 'SpMM_COO(Cupy)' ,'SpMM_CSR(Cupy)', 'SpMM_CSR(Torch)', 'SpMM_BSR(Jax)', 'SpMM_COO(Torch)', "DenseMM+Mask" 
    ]
# _ = create_single_plot_for_batches(
#     dfc, 
#     dense_level, 
#     "cuda_elapsed_time",
#     [1],
#     figsize=(7, 5), 
#     log=True,
#     title="SpMM/DenseMM (batch size = 1)",
#     batch_needed=False,
#     categories=categories,
#     ax=axes[0][2]
# )

# _ = create_single_plot_for_batches(
#     dfc, 
#     dense_level, 
#     "cuda_elapsed_time",
#     [4],
#     figsize=(7, 5), 
#     log=True,
#     title="SpMM/DenseMM (batch size = 4)",
#     batch_needed=False,
#     categories=categories,
#     ax=axes[1][2]
# )


_ = create_single_plot_for_batches(
    dfc, 
    dense_level, 
    "cuda_elapsed_time",
    [16],
    figsize=(7, 5), 
    log=True,
    title="SpMM/DenseMM (batch size = 16)",
    batch_needed=False,
       categories=categories,
    ax=axes[0][3]
)

_ = create_single_plot_for_batches(
    dfc, 
    dense_level, 
    "cuda_elapsed_time",
    [1, 32],
    figsize=(7, 5), 
    log=True,
    title="SpMM/DenseMM (batch size = 32)",
    batch_needed=False,
       categories=categories,
    ax=axes[1][3],
    legend_place="lower left",
)
for k in axes.keys():
    for v in axes[k].values():
        v.legend().set_visible(False)
legend_labels = categories
legend_colors = plt.cm.tab10.colors
from matplotlib.patches import Patch

# Create custom legend handles
custom_handles = [Patch(color=color, label=label) for color, label in zip(legend_colors, legend_labels)]
fig.legend(handles=custom_handles,
           ncol=2,
          loc='lower center',
           bbox_to_anchor=(0.5, -0.1),
           frameon=True)

# plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

fig.savefig("./figures/SpMM vs DenseMM-p2.pdf", bbox_inches='tight')
plt.show()